name: basicluckyblock
version: '1.0-SNAPSHOT'
main: org.lucky.basicluckyblock.Basicluckyblock
api-version: '1.21'
author: Mippy
commands:
  nukestick:
    description: Give the player a Nuke Stick
    usage: /<command>
  bazooka:
    description: Gives the player a Bazooka
    usage: /<command>
  suicidechestplate:
    description: Gives the player a suicide chestplate
    usage: /<command>
  aagun:
    description: Gives the player a AA Gun
    usage: /<command>
  lightningsword:
    description: Gives the player a Lightning Sword
    usage: /<command>
  bridgeegg:
    description: Gives the player a Bridge Egg
    usage: /<command>